import Head from "next/head";
import dynamic from "next/dynamic";
import { ReactNode } from "react";
import type { Metadata } from "next";
// Adjust the import path as needed
import NavBar from "./NavBar";
import Footer from "./Footer";
type LayoutProps = {
  children: ReactNode; // This ensures that children is a valid React node
};
 const metadata: Metadata = {
  metadataBase: new URL('https://leerob.io'),
  title: {
    default: 'Lee Robinson',
    template: '%s | Lee Robinson',
  },
  description: 'Developer, writer, and creator.',
  openGraph: {
    title: 'Lee Robinson',
    description: 'Developer, writer, and creator.',
    url: 'https://leerob.io',
    siteName: 'Lee Robinson',
    locale: 'en_US',
    type: 'website',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  twitter: {
    title: 'Lee Robinson',
    card: 'summary_large_image',
  },
  verification: {
    google: 'eZSdmzAXlLkKhNJzfgwDqWORghxnJ8qR9_CHdAh5-xw',
    yandex: '14d2e73487fa6c71',
  },
};
const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{children}</main> {/* Children are rendered here */}
      <Footer />
    </>
  );
};

export default Layout;
