"use client"
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { ReactNode } from 'react';

const Navbar = dynamic(() => import('./NavBar'), { ssr: false }); // Adjust the import path as needed
const Footer = dynamic(() => import('./Footer'), { ssr: false }); // Adjust the import path as needed

type LayoutProps = {
    children: ReactNode; // This ensures that children is a valid React node
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>{children}</main> {/* Children are rendered here */}
            <Footer />
        </>
    );
};

export default Layout;